name: Azure-Helloworld-Github-Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job1-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PW: ${{ secrets.DOCKER_PW}}
      run: |
       docker login -u $DOCKER_USER -p $DOCKER_PW
         
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
      id: buildx

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      id: docker_build
      with:
          context: ./
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USER}}/azure_helloworld
          
    - name: 'Azure CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: 'Run Azure CLI commands'
      run: |
          az account show
          az group list
          pwd   
          
    - name: Verify
      run: echo ${{ steps.docker_build.outputs.digest }}
